---
title: "Fig3 robustness to grid"
author: "Carl Boettiger"
date: "9/24/2015"
output: 
  md_document:
    variant: markdown_github
---

```{r, message=FALSE}
library("dplyr")
library("tidyr")
library("ggplot2")
library("multipleuncertainty")
knitr::opts_chunk$set(cache = TRUE)
```



```{r}
fig3 <- function(m, l){  
  grid <- seq(0, m, length = l)
  small     <- multiple_uncertainty(f = logistic, x_grid = grid, sigma_g = 0.1, sigma_m = 0.1, sigma_i = 0.1)
  growth    <- multiple_uncertainty(f = logistic, x_grid = grid, sigma_g = 0.5, sigma_m = 0.1, sigma_i = 0.1)
  measure   <- multiple_uncertainty(f = logistic, x_grid = grid, sigma_g = 0.1, sigma_m = 0.5, sigma_i = 0.1)
  implement <- multiple_uncertainty(f = logistic, x_grid = grid, sigma_g = 0.1, sigma_m = 0.1, sigma_i = 0.5)
  df <- data.frame(y_grid = grid, small = small, growth = growth, 
                   measure = measure, implement = implement) %>%
    tidyr::gather(scenario, value, -y_grid)
}

df <- 
data.frame(id = 1:5, 
           max    = c(150, 200, 200, 400, 300), 
           length = c(151, 201, 401, 401, 601)) %>%
  dplyr::group_by(id) %>%
  dplyr::do(fig3(.$max, .$length))

```

```{r fig.width = 9, fig.height = 12}
df %>%
  ggplot(aes(x = y_grid, y = value, col = scenario)) + 
    geom_line()  + facet_wrap(~id, ncol = 2) + 
    xlab("Stock") + ylab("Escapement") + 
    coord_cartesian(xlim = c(0, 150), ylim = c(0,100)) + 
    theme_bw() 
```

