Compare multiple uncertainties

  
```{r  setup, echo=FALSE, cache=FALSE}
require(multipleuncertainty)
require(reshape2)
require(ggplot2)
require(data.table)
````

```{r plotting, include=FALSE}
opts_knit$set(upload.fun = image_uri)
opts_chunk$set(dev.args=list(bg="transparent"), cache=FALSE, cache.path = "Sethi_Figure3/")
```

``` {r logistic}
f <- function(x,h,p){
  sapply(x, function(x){
  	S = max(x - h, 0)
  	p[1] * S * (1 - S/p[2]) + S
  })
}
````

```{r }
#pars <- c(1.5, 0.05)
#K <- (pars[1] - 1)/pars[2]

pars <- c(1,100)
K <- 100
xmin <- 0
xmax <- 1.5 * K
n_x <- 300
n_h <- n_x
x_grid <- seq(xmin, xmax, length = n_x)  
h_grid <- seq(xmin, xmax, length = n_h)
delta <- 0.05
xT <- 0
OptTime <- 20
sigma_g <- 0.3
sigma_m <- 0.3
sigma_i <- 0.3
small_noise <- 0.0
profit <- function(x,h) pmin(x, h)
pdfn = pdfn_lnorm
````

The default pdfn is uniform

```{r }
g <- SDP_multiple_uncertainty(f, pars, x_grid, h_grid, OptTime, sigmas = c(sigma_g=sigma_g, sigma_m=0, sigma_i=0), pdfn=pdfn, delta=delta)
```

```{r}
m <- SDP_multiple_uncertainty(f, pars, x_grid, h_grid, OptTime, sigmas = c(sigma_g=small_noise, sigma_m=sigma_m, sigma_i=0), pdfn=pdfn, delta=delta)  
```

```{r}
i <- SDP_multiple_uncertainty(f, pars, x_grid, h_grid, OptTime, sigmas = c(sigma_g=small_noise, sigma_m=0, sigma_i=sigma_i), pdfn=pdfn, delta=delta)  
```

Plot the policy function (in terms of escapement, `x-h`, rather than harvest `h`) at equilibrium (first time-step):

```{r policyfn_data}
require(reshape2)
policies <- melt(data.frame(stock=x_grid, g = x_grid[g$D[,1]], meas = x_grid[m$D[,1]], imp = x_grid[i$D[,1]]), id="stock")
```

```{r policyfunctions}
q1 <- ggplot(policies, aes(stock, stock - value, color=variable)) + geom_point() + xlab("stock size") + ylab("escapement") 
q1
```

